version: 1
build:
  main: cmd/osmosisd
  proto:
    path: proto
    third_party_paths:
    - third_party/proto
    - proto_vendor
accounts:
- name: validator
  coins:
  - 999999999999999uosmo
  - 999999999999999stake
  mnemonic: cinnamon legend sword giant master simple visit action level ancient day
    rubber pigeon filter garment hockey stay water crawl omit airport venture toilet
    oppose
- name: relayer
  coins:
  - 999999999999999uosmo
  - 999999999999999stake
  mnemonic: stamp later develop betray boss ranch abstract puzzle calm right bounce
    march orchard edge correct canal fault miracle void dutch lottery lucky observe
    armed
- name: faucet
  coins:
  - 999999999999999uosmo
  - 999999999999999stake
  mnemonic: lizard garlic canyon winner cheese tent drip task because ecology clay
    bridge junk critic track artefact gather harsh deliver unit vacant earth diesel
    stool
faucet:
  name: faucet
  coins:
  - 99999999999uosmo
  - 99999999999stake
  host: 0.0.0.0:4502
genesis:
  app_state:
    interchainquery:
      params:
        allow_queries:
        - /osmosis.gamm.v2.Query/SpotPrice
    interchainaccounts:
      host_genesis_state:
        params:
          allow_messages:
          - /osmosis.gamm.v1beta1.MsgSwapExactAmountIn
  chain_id: osmosis
validators:
- name: validator
  bonded: 100000000stake
  app:
    api:
      address: :1319
    grpc:
      address: :9094
    grpc-web:
      address: :9095
  config:
    p2p:
      laddr: :26661
    rpc:
      laddr: :26662
      pprof_laddr: :6062
  home: ./.osmosis

