// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: interchainswap/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgSendQueryOsmosisSpotPrice struct {
	Creator         string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	ChannelId       string `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	PoolId          uint64 `protobuf:"varint,3,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	BaseAssetDenom  string `protobuf:"bytes,4,opt,name=base_asset_denom,json=baseAssetDenom,proto3" json:"base_asset_denom,omitempty"`
	QuoteAssetDenom string `protobuf:"bytes,5,opt,name=quote_asset_denom,json=quoteAssetDenom,proto3" json:"quote_asset_denom,omitempty"`
}

func (m *MsgSendQueryOsmosisSpotPrice) Reset()         { *m = MsgSendQueryOsmosisSpotPrice{} }
func (m *MsgSendQueryOsmosisSpotPrice) String() string { return proto.CompactTextString(m) }
func (*MsgSendQueryOsmosisSpotPrice) ProtoMessage()    {}
func (*MsgSendQueryOsmosisSpotPrice) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cb2d9d84eeca56b, []int{0}
}
func (m *MsgSendQueryOsmosisSpotPrice) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSendQueryOsmosisSpotPrice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSendQueryOsmosisSpotPrice.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSendQueryOsmosisSpotPrice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSendQueryOsmosisSpotPrice.Merge(m, src)
}
func (m *MsgSendQueryOsmosisSpotPrice) XXX_Size() int {
	return m.Size()
}
func (m *MsgSendQueryOsmosisSpotPrice) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSendQueryOsmosisSpotPrice.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSendQueryOsmosisSpotPrice proto.InternalMessageInfo

func (m *MsgSendQueryOsmosisSpotPrice) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgSendQueryOsmosisSpotPrice) GetChannelId() string {
	if m != nil {
		return m.ChannelId
	}
	return ""
}

func (m *MsgSendQueryOsmosisSpotPrice) GetPoolId() uint64 {
	if m != nil {
		return m.PoolId
	}
	return 0
}

func (m *MsgSendQueryOsmosisSpotPrice) GetBaseAssetDenom() string {
	if m != nil {
		return m.BaseAssetDenom
	}
	return ""
}

func (m *MsgSendQueryOsmosisSpotPrice) GetQuoteAssetDenom() string {
	if m != nil {
		return m.QuoteAssetDenom
	}
	return ""
}

type MsgSendQueryOsmosisSpotPriceResponse struct {
	Sequence uint64 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
}

func (m *MsgSendQueryOsmosisSpotPriceResponse) Reset()         { *m = MsgSendQueryOsmosisSpotPriceResponse{} }
func (m *MsgSendQueryOsmosisSpotPriceResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSendQueryOsmosisSpotPriceResponse) ProtoMessage()    {}
func (*MsgSendQueryOsmosisSpotPriceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cb2d9d84eeca56b, []int{1}
}
func (m *MsgSendQueryOsmosisSpotPriceResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSendQueryOsmosisSpotPriceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSendQueryOsmosisSpotPriceResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSendQueryOsmosisSpotPriceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSendQueryOsmosisSpotPriceResponse.Merge(m, src)
}
func (m *MsgSendQueryOsmosisSpotPriceResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSendQueryOsmosisSpotPriceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSendQueryOsmosisSpotPriceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSendQueryOsmosisSpotPriceResponse proto.InternalMessageInfo

func (m *MsgSendQueryOsmosisSpotPriceResponse) GetSequence() uint64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

type MsgRegisterIntechainAccount struct {
	Owner        string `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	ConnectionId string `protobuf:"bytes,2,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	Version      string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
}

func (m *MsgRegisterIntechainAccount) Reset()         { *m = MsgRegisterIntechainAccount{} }
func (m *MsgRegisterIntechainAccount) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterIntechainAccount) ProtoMessage()    {}
func (*MsgRegisterIntechainAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cb2d9d84eeca56b, []int{2}
}
func (m *MsgRegisterIntechainAccount) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterIntechainAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterIntechainAccount.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterIntechainAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterIntechainAccount.Merge(m, src)
}
func (m *MsgRegisterIntechainAccount) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterIntechainAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterIntechainAccount.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterIntechainAccount proto.InternalMessageInfo

func (m *MsgRegisterIntechainAccount) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *MsgRegisterIntechainAccount) GetConnectionId() string {
	if m != nil {
		return m.ConnectionId
	}
	return ""
}

func (m *MsgRegisterIntechainAccount) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type MsgRegisterIntechainAccountResponse struct {
}

func (m *MsgRegisterIntechainAccountResponse) Reset()         { *m = MsgRegisterIntechainAccountResponse{} }
func (m *MsgRegisterIntechainAccountResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterIntechainAccountResponse) ProtoMessage()    {}
func (*MsgRegisterIntechainAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cb2d9d84eeca56b, []int{3}
}
func (m *MsgRegisterIntechainAccountResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterIntechainAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterIntechainAccountResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterIntechainAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterIntechainAccountResponse.Merge(m, src)
}
func (m *MsgRegisterIntechainAccountResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterIntechainAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterIntechainAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterIntechainAccountResponse proto.InternalMessageInfo

type MsgSendMsgOsmosisSwap struct {
	Owner        string                       `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	ConnectionId string                       `protobuf:"bytes,2,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	Msg          *OsmosisMsgSwapExactAmountIn `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (m *MsgSendMsgOsmosisSwap) Reset()         { *m = MsgSendMsgOsmosisSwap{} }
func (m *MsgSendMsgOsmosisSwap) String() string { return proto.CompactTextString(m) }
func (*MsgSendMsgOsmosisSwap) ProtoMessage()    {}
func (*MsgSendMsgOsmosisSwap) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cb2d9d84eeca56b, []int{4}
}
func (m *MsgSendMsgOsmosisSwap) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSendMsgOsmosisSwap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSendMsgOsmosisSwap.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSendMsgOsmosisSwap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSendMsgOsmosisSwap.Merge(m, src)
}
func (m *MsgSendMsgOsmosisSwap) XXX_Size() int {
	return m.Size()
}
func (m *MsgSendMsgOsmosisSwap) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSendMsgOsmosisSwap.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSendMsgOsmosisSwap proto.InternalMessageInfo

func (m *MsgSendMsgOsmosisSwap) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *MsgSendMsgOsmosisSwap) GetConnectionId() string {
	if m != nil {
		return m.ConnectionId
	}
	return ""
}

func (m *MsgSendMsgOsmosisSwap) GetMsg() *OsmosisMsgSwapExactAmountIn {
	if m != nil {
		return m.Msg
	}
	return nil
}

// MsgSubmitTxResponse defines the response for Msg/SubmitTx
type MsgSendMsgOsmosisSwapResponse struct {
}

func (m *MsgSendMsgOsmosisSwapResponse) Reset()         { *m = MsgSendMsgOsmosisSwapResponse{} }
func (m *MsgSendMsgOsmosisSwapResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSendMsgOsmosisSwapResponse) ProtoMessage()    {}
func (*MsgSendMsgOsmosisSwapResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cb2d9d84eeca56b, []int{5}
}
func (m *MsgSendMsgOsmosisSwapResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSendMsgOsmosisSwapResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSendMsgOsmosisSwapResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSendMsgOsmosisSwapResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSendMsgOsmosisSwapResponse.Merge(m, src)
}
func (m *MsgSendMsgOsmosisSwapResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSendMsgOsmosisSwapResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSendMsgOsmosisSwapResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSendMsgOsmosisSwapResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgSendQueryOsmosisSpotPrice)(nil), "tgntr.swapchain.interchainswap.MsgSendQueryOsmosisSpotPrice")
	proto.RegisterType((*MsgSendQueryOsmosisSpotPriceResponse)(nil), "tgntr.swapchain.interchainswap.MsgSendQueryOsmosisSpotPriceResponse")
	proto.RegisterType((*MsgRegisterIntechainAccount)(nil), "tgntr.swapchain.interchainswap.MsgRegisterIntechainAccount")
	proto.RegisterType((*MsgRegisterIntechainAccountResponse)(nil), "tgntr.swapchain.interchainswap.MsgRegisterIntechainAccountResponse")
	proto.RegisterType((*MsgSendMsgOsmosisSwap)(nil), "tgntr.swapchain.interchainswap.MsgSendMsgOsmosisSwap")
	proto.RegisterType((*MsgSendMsgOsmosisSwapResponse)(nil), "tgntr.swapchain.interchainswap.MsgSendMsgOsmosisSwapResponse")
}

func init() { proto.RegisterFile("interchainswap/tx.proto", fileDescriptor_6cb2d9d84eeca56b) }

var fileDescriptor_6cb2d9d84eeca56b = []byte{
	// 509 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xee, 0x92, 0xb4, 0x25, 0xc3, 0xff, 0x0a, 0xd4, 0xd4, 0xb4, 0xa6, 0x72, 0x41, 0x8a, 0x38,
	0xd8, 0xa2, 0x88, 0x53, 0xe1, 0x90, 0x52, 0x0e, 0x16, 0xb2, 0x00, 0xf7, 0xc6, 0x25, 0x72, 0xd6,
	0x23, 0xc7, 0x12, 0xde, 0x75, 0x77, 0xd7, 0x24, 0x7d, 0x05, 0x4e, 0xbc, 0x00, 0x42, 0xbc, 0x0c,
	0xe2, 0xd8, 0x03, 0x07, 0x8e, 0x28, 0x79, 0x11, 0xe4, 0x4d, 0x9c, 0x90, 0xaa, 0x0d, 0x15, 0x39,
	0xce, 0x37, 0xf3, 0xed, 0x7c, 0xdf, 0xcc, 0x68, 0x61, 0x23, 0xe5, 0x1a, 0x25, 0xeb, 0x45, 0x29,
	0x57, 0xfd, 0x28, 0xf7, 0xf4, 0xc0, 0xcd, 0xa5, 0xd0, 0x82, 0xda, 0x3a, 0xe1, 0x5a, 0xba, 0x25,
	0x68, 0xb2, 0xee, 0x7c, 0xa1, 0xb5, 0x75, 0x86, 0x28, 0x54, 0x26, 0x54, 0xaa, 0xc6, 0x6c, 0xe7,
	0x3b, 0x81, 0xad, 0x40, 0x25, 0x47, 0xc8, 0xe3, 0x77, 0x05, 0xca, 0x93, 0x37, 0xe3, 0xec, 0x51,
	0x2e, 0xf4, 0x5b, 0x99, 0x32, 0xa4, 0x4d, 0x58, 0x67, 0x12, 0x23, 0x2d, 0x64, 0x93, 0xec, 0x90,
	0x56, 0x23, 0xac, 0x42, 0xba, 0x0d, 0xc0, 0x7a, 0x11, 0xe7, 0xf8, 0xa1, 0x93, 0xc6, 0xcd, 0x2b,
	0x26, 0xd9, 0x98, 0x20, 0x7e, 0x4c, 0x37, 0x60, 0x3d, 0x17, 0xc2, 0xe4, 0x6a, 0x3b, 0xa4, 0x55,
	0x0f, 0xd7, 0xca, 0xd0, 0x8f, 0x69, 0x0b, 0x6e, 0x77, 0x23, 0x85, 0x9d, 0x48, 0x29, 0xd4, 0x9d,
	0x18, 0xb9, 0xc8, 0x9a, 0x75, 0xc3, 0xbe, 0x59, 0xe2, 0xed, 0x12, 0x3e, 0x2c, 0x51, 0xfa, 0x18,
	0xee, 0x1c, 0x17, 0x42, 0xcf, 0x97, 0xae, 0x9a, 0xd2, 0x5b, 0x26, 0x31, 0xab, 0x75, 0x0e, 0xe0,
	0xe1, 0x22, 0x1f, 0x21, 0xaa, 0x5c, 0x70, 0x85, 0xd4, 0x82, 0xab, 0x0a, 0x8f, 0x0b, 0xe4, 0x0c,
	0x8d, 0xa1, 0x7a, 0x38, 0x8d, 0x1d, 0x09, 0xf7, 0x03, 0x95, 0x84, 0x98, 0xa4, 0x4a, 0xa3, 0xf4,
	0xb9, 0x46, 0x33, 0xb6, 0x36, 0x63, 0xa2, 0xe0, 0x9a, 0xde, 0x85, 0x55, 0xd1, 0xe7, 0x58, 0x0d,
	0x62, 0x1c, 0xd0, 0x5d, 0xb8, 0xc1, 0x04, 0xe7, 0xc8, 0x74, 0x2a, 0xf8, 0x6c, 0x12, 0xd7, 0x67,
	0xa0, 0x1f, 0x97, 0x53, 0xfc, 0x88, 0x52, 0xa5, 0x82, 0x9b, 0x61, 0x34, 0xc2, 0x2a, 0x74, 0x1e,
	0xc1, 0xee, 0x82, 0x9e, 0x95, 0x6c, 0xe7, 0x1b, 0x81, 0x7b, 0x13, 0x7f, 0x81, 0x4a, 0x2a, 0x77,
	0xfd, 0x28, 0x5f, 0x46, 0x55, 0x00, 0xb5, 0x4c, 0x25, 0x46, 0xd1, 0xb5, 0xbd, 0x7d, 0x77, 0xf1,
	0x21, 0xb9, 0x93, 0xa6, 0xa5, 0x8a, 0x7e, 0x94, 0xbf, 0x1a, 0x44, 0x4c, 0xb7, 0xb3, 0x52, 0xa4,
	0xcf, 0xc3, 0xf2, 0x1d, 0xe7, 0x01, 0x6c, 0x9f, 0x2b, 0xb1, 0x32, 0xb1, 0xf7, 0xb3, 0x06, 0xb5,
	0x40, 0x25, 0xf4, 0x2b, 0x81, 0xcd, 0x8b, 0x2f, 0xee, 0xf9, 0xbf, 0x84, 0x2c, 0xda, 0xb3, 0x75,
	0xb8, 0x0c, 0x7b, 0x7a, 0x25, 0x5f, 0x08, 0x6c, 0xfe, 0xbd, 0x13, 0x39, 0x77, 0x08, 0xfb, 0x97,
	0xe8, 0x71, 0xd1, 0x46, 0xad, 0x97, 0x4b, 0x90, 0xa7, 0xfa, 0x3e, 0x11, 0xa0, 0xe7, 0xdc, 0xc2,
	0xb3, 0x4b, 0x9a, 0x9f, 0xa7, 0x59, 0x2f, 0xfe, 0x8b, 0x56, 0x89, 0x39, 0x78, 0xfd, 0x63, 0x68,
	0x93, 0xd3, 0xa1, 0x4d, 0x7e, 0x0f, 0x6d, 0xf2, 0x79, 0x64, 0xaf, 0x9c, 0x8e, 0xec, 0x95, 0x5f,
	0x23, 0x7b, 0xe5, 0xfd, 0x93, 0x24, 0xd5, 0xbd, 0xa2, 0xeb, 0x32, 0x91, 0x79, 0xa6, 0x85, 0x37,
	0x6d, 0xe1, 0x0d, 0xbc, 0xb3, 0x3f, 0xda, 0x49, 0x8e, 0xaa, 0xbb, 0x66, 0xfe, 0xa5, 0xa7, 0x7f,
	0x02, 0x00, 0x00, 0xff, 0xff, 0x57, 0xb1, 0x3a, 0xdb, 0xf0, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	SendQueryOsmosisSpotPrice(ctx context.Context, in *MsgSendQueryOsmosisSpotPrice, opts ...grpc.CallOption) (*MsgSendQueryOsmosisSpotPriceResponse, error)
	RegisterInterchainAccount(ctx context.Context, in *MsgRegisterIntechainAccount, opts ...grpc.CallOption) (*MsgRegisterIntechainAccountResponse, error)
	SendMsgOsmosisSwap(ctx context.Context, in *MsgSendMsgOsmosisSwap, opts ...grpc.CallOption) (*MsgSendMsgOsmosisSwapResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) SendQueryOsmosisSpotPrice(ctx context.Context, in *MsgSendQueryOsmosisSpotPrice, opts ...grpc.CallOption) (*MsgSendQueryOsmosisSpotPriceResponse, error) {
	out := new(MsgSendQueryOsmosisSpotPriceResponse)
	err := c.cc.Invoke(ctx, "/tgntr.swapchain.interchainswap.Msg/SendQueryOsmosisSpotPrice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RegisterInterchainAccount(ctx context.Context, in *MsgRegisterIntechainAccount, opts ...grpc.CallOption) (*MsgRegisterIntechainAccountResponse, error) {
	out := new(MsgRegisterIntechainAccountResponse)
	err := c.cc.Invoke(ctx, "/tgntr.swapchain.interchainswap.Msg/RegisterInterchainAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SendMsgOsmosisSwap(ctx context.Context, in *MsgSendMsgOsmosisSwap, opts ...grpc.CallOption) (*MsgSendMsgOsmosisSwapResponse, error) {
	out := new(MsgSendMsgOsmosisSwapResponse)
	err := c.cc.Invoke(ctx, "/tgntr.swapchain.interchainswap.Msg/SendMsgOsmosisSwap", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	SendQueryOsmosisSpotPrice(context.Context, *MsgSendQueryOsmosisSpotPrice) (*MsgSendQueryOsmosisSpotPriceResponse, error)
	RegisterInterchainAccount(context.Context, *MsgRegisterIntechainAccount) (*MsgRegisterIntechainAccountResponse, error)
	SendMsgOsmosisSwap(context.Context, *MsgSendMsgOsmosisSwap) (*MsgSendMsgOsmosisSwapResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) SendQueryOsmosisSpotPrice(ctx context.Context, req *MsgSendQueryOsmosisSpotPrice) (*MsgSendQueryOsmosisSpotPriceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendQueryOsmosisSpotPrice not implemented")
}
func (*UnimplementedMsgServer) RegisterInterchainAccount(ctx context.Context, req *MsgRegisterIntechainAccount) (*MsgRegisterIntechainAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterInterchainAccount not implemented")
}
func (*UnimplementedMsgServer) SendMsgOsmosisSwap(ctx context.Context, req *MsgSendMsgOsmosisSwap) (*MsgSendMsgOsmosisSwapResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMsgOsmosisSwap not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_SendQueryOsmosisSpotPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSendQueryOsmosisSpotPrice)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SendQueryOsmosisSpotPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tgntr.swapchain.interchainswap.Msg/SendQueryOsmosisSpotPrice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SendQueryOsmosisSpotPrice(ctx, req.(*MsgSendQueryOsmosisSpotPrice))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RegisterInterchainAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRegisterIntechainAccount)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RegisterInterchainAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tgntr.swapchain.interchainswap.Msg/RegisterInterchainAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RegisterInterchainAccount(ctx, req.(*MsgRegisterIntechainAccount))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SendMsgOsmosisSwap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSendMsgOsmosisSwap)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SendMsgOsmosisSwap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tgntr.swapchain.interchainswap.Msg/SendMsgOsmosisSwap",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SendMsgOsmosisSwap(ctx, req.(*MsgSendMsgOsmosisSwap))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tgntr.swapchain.interchainswap.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendQueryOsmosisSpotPrice",
			Handler:    _Msg_SendQueryOsmosisSpotPrice_Handler,
		},
		{
			MethodName: "RegisterInterchainAccount",
			Handler:    _Msg_RegisterInterchainAccount_Handler,
		},
		{
			MethodName: "SendMsgOsmosisSwap",
			Handler:    _Msg_SendMsgOsmosisSwap_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "interchainswap/tx.proto",
}

func (m *MsgSendQueryOsmosisSpotPrice) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSendQueryOsmosisSpotPrice) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSendQueryOsmosisSpotPrice) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.QuoteAssetDenom) > 0 {
		i -= len(m.QuoteAssetDenom)
		copy(dAtA[i:], m.QuoteAssetDenom)
		i = encodeVarintTx(dAtA, i, uint64(len(m.QuoteAssetDenom)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.BaseAssetDenom) > 0 {
		i -= len(m.BaseAssetDenom)
		copy(dAtA[i:], m.BaseAssetDenom)
		i = encodeVarintTx(dAtA, i, uint64(len(m.BaseAssetDenom)))
		i--
		dAtA[i] = 0x22
	}
	if m.PoolId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.PoolId))
		i--
		dAtA[i] = 0x18
	}
	if len(m.ChannelId) > 0 {
		i -= len(m.ChannelId)
		copy(dAtA[i:], m.ChannelId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ChannelId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSendQueryOsmosisSpotPriceResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSendQueryOsmosisSpotPriceResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSendQueryOsmosisSpotPriceResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Sequence != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Sequence))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgRegisterIntechainAccount) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterIntechainAccount) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterIntechainAccount) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Version) > 0 {
		i -= len(m.Version)
		copy(dAtA[i:], m.Version)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Version)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ConnectionId) > 0 {
		i -= len(m.ConnectionId)
		copy(dAtA[i:], m.ConnectionId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ConnectionId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRegisterIntechainAccountResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterIntechainAccountResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterIntechainAccountResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgSendMsgOsmosisSwap) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSendMsgOsmosisSwap) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSendMsgOsmosisSwap) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Msg != nil {
		{
			size, err := m.Msg.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ConnectionId) > 0 {
		i -= len(m.ConnectionId)
		copy(dAtA[i:], m.ConnectionId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ConnectionId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSendMsgOsmosisSwapResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSendMsgOsmosisSwapResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSendMsgOsmosisSwapResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgSendQueryOsmosisSpotPrice) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ChannelId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.PoolId != 0 {
		n += 1 + sovTx(uint64(m.PoolId))
	}
	l = len(m.BaseAssetDenom)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.QuoteAssetDenom)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgSendQueryOsmosisSpotPriceResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Sequence != 0 {
		n += 1 + sovTx(uint64(m.Sequence))
	}
	return n
}

func (m *MsgRegisterIntechainAccount) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ConnectionId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Version)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgRegisterIntechainAccountResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgSendMsgOsmosisSwap) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ConnectionId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Msg != nil {
		l = m.Msg.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgSendMsgOsmosisSwapResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgSendQueryOsmosisSpotPrice) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSendQueryOsmosisSpotPrice: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSendQueryOsmosisSpotPrice: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChannelId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChannelId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolId", wireType)
			}
			m.PoolId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PoolId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BaseAssetDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BaseAssetDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field QuoteAssetDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.QuoteAssetDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSendQueryOsmosisSpotPriceResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSendQueryOsmosisSpotPriceResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSendQueryOsmosisSpotPriceResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sequence", wireType)
			}
			m.Sequence = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Sequence |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRegisterIntechainAccount) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterIntechainAccount: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterIntechainAccount: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConnectionId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ConnectionId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Version", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Version = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRegisterIntechainAccountResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterIntechainAccountResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterIntechainAccountResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSendMsgOsmosisSwap) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSendMsgOsmosisSwap: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSendMsgOsmosisSwap: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConnectionId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ConnectionId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Msg", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Msg == nil {
				m.Msg = &OsmosisMsgSwapExactAmountIn{}
			}
			if err := m.Msg.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSendMsgOsmosisSwapResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSendMsgOsmosisSwapResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSendMsgOsmosisSwapResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
